import uuid
from typing import List, Dict, Any
from src.memory.storage import ChromaStorage

class MemoryBank:
    def __init__(self):
        self.storage = ChromaStorage()

    def add_lesson(self, lesson: str, category: str, source: str):
        """
        Stores a 'Lesson Learned' (e.g., a successful attack pattern or a defense rule).
        """
        doc_id = str(uuid.uuid4())
        self.storage.add(
            documents=[lesson],
            metadatas=[{"category": category, "source": source, "type": "lesson"}],
            ids=[doc_id]
        )

    def add_attack_vector(self, prompt: str, success: bool):
        """
        Stores an attack vector for future reference.
        """
        doc_id = str(uuid.uuid4())
        self.storage.add(
            documents=[prompt],
            metadatas=[{"category": "attack_vector", "success": success, "type": "attack"}],
            ids=[doc_id]
        )

    def find_relevant_lessons(self, query: str, n: int = 3) -> List[str]:
        """
        Retrieves lessons relevant to the current context.
        """
        results = self.storage.query(query, n_results=n)
        if results and results['documents']:
            return results['documents'][0]
        return []
    
    def get_relevant_attacks(self, query: str, n: int = 3) -> List[str]:
        """
        Retrieves successful attack vectors similar to the query.
        """
        results = self.storage.query(query, n_results=n)
        if results and results['documents'] and results['metadatas']:
            # Filter for successful attacks only
            attacks = []
            for doc, meta in zip(results['documents'][0], results['metadatas'][0]):
                if meta.get('type') == 'attack' and meta.get('success'):
                    attacks.append(doc)
            return attacks[:n]
        return []
    
    def get_defense_strategies(self, query: str, n: int = 3) -> List[str]:
        """
        Retrieves defense lessons and strategies relevant to the query.
        """
        results = self.storage.query(query, n_results=n)
        if results and results['documents'] and results['metadatas']:
            # Filter for defense-related lessons
            strategies = []
            for doc, meta in zip(results['documents'][0], results['metadatas'][0]):
                if meta.get('category') in ['defense_gap', 'defensive_weakness']:
                    strategies.append(doc)
            return strategies[:n]
        return []
    
    def add_reflection(self, insight: Dict[str, str]):
        """
        Stores a reflection/insight generated by the Reflector Agent.
        """
        doc_id = str(uuid.uuid4())
        self.storage.add(
            documents=[insight.get('content', '')],
            metadatas=[{
                'type': insight.get('type', 'reflection'),
                'category': insight.get('category', 'general'),
                'source': 'reflector_agent'
            }],
            ids=[doc_id]
        )

